### PR TITLE
Fix formatting

### PR DESCRIPTION
**Pull request by arinthros**
Fixes a formatting bug when upgrading.

### CODE REVIEW

**Comment by TheRedPanda17** [comment]
If you can confirm the fix with screenshot, I'll merge it

**Comment by rj-lee** [comment]
I'd like to know where you were seeing this bug happen that needed the tag to be closed explicitly so I can look out for them in the future

**Comment by rj-lee** [comment]
@arinthros I saw your screenshot on discord, I actually fixed this bug in #51, perhaps you were just about to pull that update when this bug happened? Try manually pulling main, then commenting out everything before [line 42 in utilities/git.py](https://github.com/TheRedPanda17/myning/blob/main/myning/utilities/git.py#L42) to see if it works?

**Comment by TheRedPanda17** [comment]
I can confirm this is no longer an issue.

**Pull request closed without merging**
