### PR TITLE
remove entity files

### PR DESCRIPTION
**Pull request by chrisvaughn**
* all information in entities is persisted in player.json
* the files never seemed to be cleaned up or loaded from

### CODE REVIEW

**Comment by chrisvaughn** [comment]
@TheRedPanda17 while I was working through the race -> species data migration I found that these entity files aren't read in, just written to. I looks like everything works without them.  I'm not sure if this is an old way of managing files that's no longer needed or if it's a partial implementation of something new to take data out of player.json.  Feel free to close if you want it how it was.  I'm learning the code base by making changes.

**Comment by TheRedPanda17** [comment]
This _is_ an artifact of how we used to read in data, but it also might be what we return to. We've been trying to simplify the `player.json` file and the `Player` class, and just storing a list of IDs for entities would get us closer to that. I'm going to close this for now. Thanks for trying to remove redundancy.

**Comment by chrisvaughn** [comment]
Would you like for me to work on simplifying the player object?

**Comment by TheRedPanda17** [comment]
> Would you like for me to work on simplifying the player object?

If you'd like to! We've been separating code out into their own singletons. The end goal is to move to SQLite, so keep that in mind. 

A good place to start might be to create a `Graveyard` singleton and put `soul_credits` and `fallen_allies` in there. Something like what I did for the macguffin: https://github.com/TheRedPanda17/myning/pull/22

**Pull request closed without merging**
