### PR TITLE
Added compact mode

### PR DESCRIPTION
**Pull request by TheRedPanda17**
I actually don't know if I want this or not. What do you guys think?

### CODE REVIEW

**Comment by TheRedPanda17** [comment]
Screen Shot 2023-08-01 at 5 29 45 PM
Screen Shot 2023-08-01 at 5 30 37 PM

**Comment by rj-lee** [comment]
I like that it makes the game more playable on smaller terminal sizes for that split-screen quality of life, although I usually have mine fullscreen and bring it to the foreground when necessary instead of keeping an eye on it at all times. We currently have the option to toggle the army in the dashboard but this would be a nice improvement. 

Some ideas:
- What if the army toggle in the dashboard toggled between full and compact?
- What if the character with the highest health + damage + defense was the representative?
  - or all the character icons could be lined up in a row?

I feel like most of the benefit comes from the menu dashboard improvement, not so much the combat screen for a few reasons: because people don't pay much attention to that, each frame already refreshes the screen, and there's nothing else that we need that screen space for during combat. In high-level mines seeing the huge army you're up against is also fun in a way, reducing it down to just a number (17 vs 23) limits that a little. So not sure that it warrants an actual setting option if we only had the compact view for the dashboard toggle. Not opposed if you want to keep it this way though

**Comment by TheRedPanda17** [comment]
@rj-lee I like the idea of icons. Instead of condensing it to a single number and icon, just do one more line of all the character icons. Then you still get the feel for how big the army is

**Comment by TheRedPanda17** [comment]
Screen Shot 2023-08-01 at 8 24 06 PM

**Review by rj-lee — APPROVED** [review]

**Pull request merged**
